version: '3.9'

services:
  traefik:
    container_name: traefik
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"

  php-apache:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php-apache.rule=Host(`test-apache.local`)"
      - "traefik.http.services.php-apache.loadbalancer.server.port=80"
    volumes:
      - ./apache-config:/etc/apache2/sites-available
      - ./:/var/www/html
    networks:
      - test-network

networks:
  test-network:
    external: true
