version: '3'
services:

  # Node.js application service
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  # MySQL database service  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: your_database
      MYSQL_USER: username 
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  # phpmyadmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: username
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql-data: